rtl/Adder.v
rtl/PCplus4.v
rtl/program_counter.v
rtl/Mux1.v
rtl/Mux2.v
rtl/Mux3.v
rtl/AND_logic.v
rtl/Control_Unit.v
rtl/ALU_Control.v
rtl/ALU_unit.v
rtl/immediate_generator.v
rtl/Register_File.v
rtl/wb_master_lsu.v
rtl/riscv_core.v
rtl/wb_addr_decoder.v
rtl/wb_read_mux.v
rtl/wb_prog_mem_slave.v
rtl/wb_data_mem_slave.v
rtl/wb_gpio_slave.v
rtl/riscv_soc.v
sim/riscv_soc_tb.v
